<?php
$formatMetric = static fn(array $item): string => $item['format'] === 'money'
    ? '$' . number_format((float) $item['value'], 0, ',', '.')
    : number_format((float) $item['value'], $item['format'] === 'decimal' ? 2 : 0, ',', '.');
?>
<div class="page-intro page-intro-actions"><div><span class="section-kicker">Inteligencia de negocio</span><h2>Reportes ejecutivos</h2><p>Consolidado operacional, financiero, de personas y cumplimiento para el período seleccionado.</p></div><a class="btn btn-outline-primary" href="<?= e(url('/reports/export?from=' . $from . '&to=' . $to)) ?>"><i class="bi bi-filetype-csv"></i>Exportar CSV</a></div>
<section class="app-card mb-4"><form class="report-filter" method="get" action="<?= e(url('/reports')) ?>"><div><label class="form-label" for="from">Desde</label><input class="form-control" type="date" id="from" name="from" value="<?= e($from) ?>" required></div><div><label class="form-label" for="to">Hasta</label><input class="form-control" type="date" id="to" name="to" value="<?= e($to) ?>" required></div><button class="btn btn-primary" type="submit"><i class="bi bi-funnel"></i>Aplicar período</button></form></section>
<?php if ($databaseError): ?><div class="migration-callout"><span><i class="bi bi-database-exclamation"></i></span><div><strong>Datos aún no disponibles</strong><p><?= e($databaseError) ?></p></div></div><?php endif; ?>
<div class="report-grid mb-4"><?php foreach ($metrics as $item): ?><article class="report-metric"><span><i class="bi <?= e($item['icon']) ?>"></i></span><div><small><?= e($item['label']) ?></small><strong><?= e($formatMetric($item)) ?></strong></div></article><?php endforeach; ?></div>
<section class="app-card table-card"><div class="card-heading report-heading"><div><span class="section-kicker">Cartera comercial</span><h3>Facturación por cliente</h3></div><span class="period-chip"><i class="bi bi-calendar-range"></i><?= e(date('d/m/Y', strtotime($from))) ?> – <?= e(date('d/m/Y', strtotime($to))) ?></span></div><div class="table-responsive"><table class="table app-table mb-0"><thead><tr><th>Cliente</th><th>Documentos</th><th>Facturación</th><th>Saldo</th></tr></thead><tbody><?php if ($clients === []): ?><tr><td colspan="4"><div class="empty-state"><span><i class="bi bi-bar-chart"></i></span><strong>Sin facturación para el período</strong><p>Cambia las fechas o registra documentos de venta.</p></div></td></tr><?php else: foreach ($clients as $client): ?><tr><td><strong><?= e($client['business_name']) ?></strong></td><td><?= e($client['documents']) ?></td><td>$<?= e(number_format((float) $client['total'], 0, ',', '.')) ?></td><td>$<?= e(number_format((float) $client['balance'], 0, ',', '.')) ?></td></tr><?php endforeach; endif; ?></tbody></table></div></section>
